Repository CodeSoom-Project/my-seat, pull requests merged in 2022-09, with the labels that each got.

#151 일부 디자인 수정
  app-web/src/Header.tsx
  app-web/src/LogOutForm.tsx
  app-web/src/LoginForm.tsx
  app-web/src/index.css
  app-web/src/signIn.tsx
  app-web/src/signUp.tsx
Labels: frontend, chore

#152 Security 수정
  app-server/app/src/main/java/com/codesoom/myseat/config/SecurityConfig.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/LoginController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatAddController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatDetailController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationCancelController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationListController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SignupController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Role.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/filters/AuthenticationFilter.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/RoleRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/security/UserAuthentication.java
  app-server/app/src/main/java/com/codesoom/myseat/services/AuthenticationService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatDetailService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationCancelService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SignupService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/UserService.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/JwtUtil.java
  app-server/app/src/main/resources/application.yml
  app-server/app/src/test/java/com/codesoom/myseat/controllers/LoginControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SignupControllerTest.java
Labels: backend, chore

#154 로그아웃 버튼을 누르면 로그인 버튼으로 바뀌어라
  app-web/src/Header.tsx
  app-web/src/HeaderContainer.tsx
Labels: feature, frontend

#153 모달 창 클릭시 모달 창이 꺼지게 만들기
  app-web/src/ReservationListContainer.tsx
  app-web/src/components/CheckOutsideClick.tsx
  app-web/src/components/Modal.tsx
  app-web/src/seatDetailModal.tsx
Labels: refactor, frontend

#158 테스트 할 수 있는 환경을 만들어라
  app-web/.babel.config.js
  app-web/.eslintrc.cjs
  app-web/.eslintrc.json
  app-web/__mocks__/fileMocks.js
  app-web/__mocks__/styleMock.js
  app-web/jest.config.mjs
  app-web/jest.setup.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/App.test.tsx
  app-web/src/test/__mocks__/fileMock.js
  app-web/tsconfig.json
Labels: setting, frontend, test

#160 용어 수정
  app-server/app/src/main/java/com/codesoom/myseat/controllers/LoginController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatDetailController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatListController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationCancelController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationController.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationListController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Seat.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/LoginResponse.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/SeatDetailResponse.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/SeatListResponse.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/SeatReservationResponse.java
  app-server/app/src/main/java/com/codesoom/myseat/filters/AuthenticationFilter.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/SeatReservationRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/UserRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/services/AuthenticationService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatDetailService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationCancelService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationService.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/JwtUtil.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/LoginControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatDetailControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatListControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationListControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/AuthenticationServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatDetailServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatListServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationCancelServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationListServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationServiceTest.java
Labels: backend, chore
