Repository CodeSoom-Project/my-seat, pull requests merged in 2022-08, with the labels that each got.

#104 로그인 기능 구현
  app-server/app/build.gradle
  app-server/app/src/main/java/com/codesoom/myseat/config/SecurityConfig.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/LoginController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/UserRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/LoginRequest.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/LoginResponse.java
  app-server/app/src/main/java/com/codesoom/myseat/exceptions/LoginFailureException.java
  app-server/app/src/main/java/com/codesoom/myseat/exceptions/UserNotFoundException.java
  app-server/app/src/main/java/com/codesoom/myseat/services/LoginService.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/TokenProvider.java
  app-server/app/src/main/resources/application.yml
  app-server/app/src/test/java/com/codesoom/myseat/controllers/LoginControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/LoginServiceTest.java
Labels: feature, backend

#106 회원 가입, 로그인 REST Docs 작성
  app-server/app/src/docs/asciidoc/index.adoc
  app-server/app/src/main/resources/static/docs/index.html
  app-server/app/src/test/java/com/codesoom/myseat/controllers/LoginControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SignupControllerTest.java
Labels: docs, backend

#108 회원가입 비밀번호 체크가 필요합니다.
  app-web/package-lock.json
  app-web/package.json
  app-web/src/admin.tsx
  app-web/src/api.ts
  app-web/src/authSlice.ts
  app-web/src/main.tsx
  app-web/src/signInContainer.tsx
  app-web/src/signUp.tsx
  app-web/src/signUpContainer.tsx
  app-web/src/store.ts
Labels: feature, refactor, frontend

#109 Updates
  assets/index.a09295fe.js
  assets/index.e9a78244.js
  index.html
Labels: frontend

#110 Updates
  assets/index.b6715fbb.js
  index.html
Labels: frontend

#111 Updates
  index.html
Labels: frontend

#112 Updates
  index.html
Labels: frontend

#118 로그인 후 accessToken 저장하기
  app-web/src/App.tsx
  app-web/src/components/Header.tsx
  app-web/src/main.tsx
  app-web/src/signInContainer.tsx
  app-web/src/signUpContainer.tsx
Labels: feature, frontend

#119 로그아웃
  app-web/src/App.tsx
  app-web/src/LogOutForm.tsx
  app-web/src/LoginForm.tsx
  app-web/src/authSlice.ts
  app-web/src/components/Header.tsx
  app-web/src/signInContainer.tsx
Labels: feature, frontend

#122 좌석 상세 조회 API 문서 작성
  app-server/app/src/docs/asciidoc/index.adoc
  app-server/app/src/main/resources/static/docs/index.html
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatDetailControllerTest.java
Labels: docs, backend

#123 좌석 목록 보여주기
  .idea/jsLinters/eslint.xml
  app-web/.eslintrc.ts
  app-web/package-lock.json
  app-web/package.json
  app-web/src/App.tsx
  app-web/src/api.ts
  app-web/src/seatList.tsx
Labels: feature, frontend

#124 배포를 바로 upstream으로 하고싶습니다.
  app-web/package.json
  app-web/src/main.tsx
Labels: setting, frontend

#126 MockMvcRequestBuilders를 RestDocumentationBuilders로수정
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatDetailControllerTest.java
Labels: fix, backend

#128 로그인 실패 오류 수정
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/http-request/local/login.http
  app-server/http-request/server/login.http
  app-server/http-request/server/seat-add.http
Labels: fix, backend

#129 예약 내역이 없는 경우 상태 코드 200을 응답하도록 수정
  app-server/app/src/main/java/com/codesoom/myseat/controllers/ControllerErrorAdvice.java
Labels: feature, backend

#130 회원 가입 시 비밀번호를 암호화 하는 로직 추가
  app-server/app/src/main/java/com/codesoom/myseat/config/ApplicationConfig.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SignupService.java
Labels: feature, backend

#131 회원 가입 테스트 코드에 PasswordEncoder 추가
  app-server/app/src/test/java/com/codesoom/myseat/services/SignupServiceTest.java
Labels: backend, test

#134 예약 내역이 없는 경우 에러 메시지가 아닌 빈 배열을 응답하도록 수정
  app-server/app/src/main/java/com/codesoom/myseat/controllers/ControllerErrorAdvice.java
  app-server/http-request/local/seat-reservations.http
  app-server/http-request/server/seat-reservations.http
  http-request/seat-add.http
Labels: feature, backend

#136 좌석 예약 여부 초기화 스케줄러 추가
  app-server/app/src/main/java/com/codesoom/myseat/App.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Seat.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/SeatRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/ScheduledTasks.java
  app-server/http-request/local/seat-detail.http
  app-server/http-request/local/seat-reservation.http
  app-server/http-request/local/seats.http
  app-server/http-request/server/seat-detail.http
  app-server/http-request/server/seats.http
Labels: feature, backend

#137 좌석 상세조회를 할 수 있는 modal이 필요합니다.
  .idea/jsLinters/eslint.xml
  app-web/.eslintignore
  app-web/.eslintrc.cjs
  app-web/.eslintrc.ts
  app-web/index.html
  app-web/package-lock.json
  app-web/package.json
  app-web/src/App.tsx
  app-web/src/LogOutForm.tsx
  app-web/src/LoginForm.tsx
  app-web/src/NotFound.tsx
  app-web/src/ReservationForm.tsx
  app-web/src/ReservationFormContainer.tsx
  app-web/src/ReservationItem.tsx
  app-web/src/ReservationList.tsx
  app-web/src/ReservationListContainer.tsx
  app-web/src/ReservationSlice.ts
  app-web/src/Users.tsx
  app-web/src/admin.tsx
  app-web/src/api.ts
  app-web/src/authSlice.ts
  app-web/src/components/Button.tsx
  app-web/src/components/Header.tsx
  app-web/src/components/Modal.tsx
  app-web/src/components/ReservationButton.tsx
  app-web/src/components/details.tsx
  app-web/src/hooks.ts
  app-web/src/main.tsx
  app-web/src/seatDetailModal.tsx
  app-web/src/seatDetailsModalContainer.tsx
  app-web/src/seatList.tsx
  app-web/src/services/api.ts
  app-web/src/services/stoage.ts
  app-web/src/signIn.tsx
  app-web/src/signInContainer.tsx
  app-web/src/signUp.tsx
  app-web/src/signUpContainer.tsx
  app-web/src/store.ts
Labels: feature, frontend

#138 API 요청시 토큰이 필요합니다.
  app-web/src/services/api.ts
  app-web/src/signInContainer.tsx
Labels: feature, frontend

#139 modal 에서 예약버튼이 필요합니다.
  app-web/src/ReservationButton.tsx
  app-web/src/components/ReservationButton.tsx
  app-web/src/seatDetailModal.tsx
  app-web/src/seatDetailsModalContainer.tsx
  app-web/src/seatList.tsx
Labels: feature, frontend

#140 엔티티 간 연관 관계 매핑, 로그인 로직 수정
  app-server/app/src/main/java/com/codesoom/myseat/controllers/ControllerErrorAdvice.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/LoginController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Seat.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/SeatReservation.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Token.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/SeatRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/SeatReservationRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/TokenRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/UserRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/services/LoginService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatAddService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatDetailService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatListService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationCancelService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationListService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SignupService.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/ScheduledTasks.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/LoginControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/LoginServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatAddServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatDetailServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatListServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationCancelServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationListServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationServiceTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SignupServiceTest.java
  app-server/http-request/local/seat-add.http
  app-server/http-request/local/signup.http
Labels: refactor, backend

#142 회원 가입 시 user 권한 부여하는 코드 추가
  app-server/app/src/main/java/com/codesoom/myseat/domain/Role.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SignupService.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SignupServiceTest.java
Labels: feature, backend

#145 Spring Security 설정 및 인증 로직 수정
  app-server/app/src/main/java/com/codesoom/myseat/config/SecurityConfig.java
  app-server/app/src/main/java/com/codesoom/myseat/controllers/LoginController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Token.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/filters/AuthenticationFilter.java
  app-server/app/src/main/java/com/codesoom/myseat/repositories/TokenRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/services/LoginService.java
  app-server/app/src/main/java/com/codesoom/myseat/services/UserService.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/JwtUtil.java
  app-server/app/src/main/java/com/codesoom/myseat/utils/TokenProvider.java
Labels: feature, backend

#146 좌석 상세 조회
  app-web/package-lock.json
  app-web/package.json
  app-web/src/App.tsx
  app-web/src/ReservationListContainer.tsx
  app-web/src/ReservationSlice.ts
  app-web/src/SelectTime.tsx
  app-web/src/SelectTimeContainer.tsx
  app-web/src/components/details.tsx
  app-web/src/seatDetailModal.tsx
  app-web/src/seatDetailModalContainer.tsx
  app-web/src/seatDetailsModalContainer.tsx
  app-web/src/seatList.tsx
  app-web/src/services/api.ts
Labels: feature, frontend

#147 Header 분리
  app-web/src/App.tsx
  app-web/src/Header.tsx
  app-web/src/HeaderContainer.tsx
  app-web/src/components/Header.tsx
  app-web/src/signInContainer.tsx
  app-web/src/signUpContainer.tsx
Labels: feature, frontend

#148 나의 자리인지 확인
  app-web/src/seatDetailModal.tsx
  app-web/src/seatList.tsx
  app-web/src/services/api.ts
Labels: feature, frontend
