Repository CodeSoom-Project/my-seat, pull requests merged in 2022-07, with the labels that each got.

#10 좌석 추가, 예약 추가 테스트 코드 실패 오류 수정
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatAddControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationServiceTest.java
Labels: fix

#12 Docker 이미지 생성 실패 오류 수정
  app-server/Dockerfile
Labels: fix

#26 좌석 추가, 좌석 예약, 좌석 예약 목록 조회에 대한 REST Docs 작성
  app-server/app/build.gradle
  app-server/app/src/docs/asciidoc/index.adoc
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationController.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatAddControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationListControllerTest.java
Labels: docs, backend

#33 #issue 30 name을 전달하기
  app-web/src/ReservationForm.tsx
  app-web/src/ReservationFormContainer.tsx
Labels: fix, frontend

#34 name state명 변경하기
  app-web/src/ReservationForm.tsx
  app-web/src/ReservationFormContainer.tsx
  app-web/src/ReservationSlice.ts
Labels: fix, frontend

#36 eslint 설정 변경
  app-web/.eslintrc.js
  app-web/babel.config.js
  app-web/jest.config.ts
  app-web/package-lock.json
  app-web/package.json
  app-web/src/App.tsx
  app-web/src/Header.tsx
  app-web/src/ReservationForm.tsx
  app-web/src/ReservationFormContainer.tsx
  app-web/src/ReservationSlice.ts
  app-web/src/hooks.ts
  app-web/src/store.ts
Labels: setting, frontend

#37 좌석 예약 취소 기능 구현
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationCancelController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/Seat.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/SeatReservationRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/SeatReservationCancelRequest.java
  app-server/app/src/main/java/com/codesoom/myseat/exceptions/SeatReservationNotFoundException.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationCancelService.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationCancelControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationCancelServiceTest.java
Labels: feature, backend

#40 Dockerfile 수정
  app-server/Dockerfile
Labels: fix, backend

#38 예약된 좌석 보여주기
  app-web/index.html
  app-web/src/App.tsx
  app-web/src/ReservationForm.tsx
  app-web/src/ReservationFormContainer.tsx
  app-web/src/ReservationItem.tsx
  app-web/src/ReservationList.tsx
  app-web/src/ReservationListContainer.tsx
  app-web/src/components/Button.tsx
  app-web/src/main.tsx
  app-web/src/reservationApi.ts
  app-web/tsconfig.json
  app-web/vite.config.ts
Labels: feature, frontend

#43 H2 인메모리 DB 세팅
  app-server/app/src/main/resources/application.yml
  app-server/app/src/main/resources/schema.sql
Labels: setting, backend

#44 좌석 예약 목록 조회 리팩토링
  app-web/src/ReservationListContainer.tsx
  app-web/src/reservationApi.ts
Labels: refactor, frontend

#47 좌석 예약 여부 확인 방법 변경
  app-server/app/src/main/java/com/codesoom/myseat/domain/Seat.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationService.java
Labels: feature, backend

#48 useQuery 로직 수정
  app-web/src/ReservationList.tsx
  app-web/src/ReservationListContainer.tsx
  app-web/src/reservationApi.ts
Labels: fix, frontend

#46 좌석 목록 조회 기능 구현
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatListController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/SeatRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/SeatListResponse.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatListService.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatListControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatListServiceTest.java
Labels: feature, backend

#53 컬럼을 찾지 못하는 오류 수정
  app-server/app/src/main/java/com/codesoom/myseat/controllers/ControllerErrorAdvice.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/SeatReservationRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationListService.java
  app-server/app/src/main/resources/application.yml
  app-server/app/src/main/resources/schema.sql
Labels: fix, backend

#55 생성된 REST Docs html 문서를 static/docs로 복사하는 설정 추가
  app-server/app/build.gradle
Labels: setting, backend

#54 좌석 예약 목록 조회 수정
  app-web/src/ReservationListContainer.tsx
  app-web/src/reservationApi.ts
Labels: fix, frontend

#56 좌석 예약 취소 시 상태 코드만 응답하도록 수정
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SeatReservationCancelController.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationCancelControllerTest.java
Labels: feature, backend

#58 좌석 예약 목록 조회 서비스 테스트 코드에서 List.of() 부분 컴파일 오류 수정
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationListServiceTest.java
Labels: fix, backend

#60 좌석 목록 조회, 좌석 예약 취소 REST Docs 작성
  app-server/app/src/docs/asciidoc/index.adoc
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatAddControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatListControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationCancelControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SeatReservationListControllerTest.java
Labels: docs, backend

#65 Update gh-pages
  asset-manifest.json
  assets/index.a7a510eb.js
  assets/index.e88c1300.css
  index.html
  manifest.json
  robots.txt
  static/css/main.964fdded.css
  static/css/main.964fdded.css.map
  static/js/787.1fdc35ac.chunk.js
  static/js/787.1fdc35ac.chunk.js.map
  static/js/main.c2ff72c8.js
  static/js/main.c2ff72c8.js.LICENSE.txt
  static/js/main.c2ff72c8.js.map
Labels: frontend

#66 meta 추가
  app-web/index.html
Labels: fix, frontend

#70 Update gh-pages
  assets/index.a7a510eb.js
  assets/index.fe98a633.js
  index.html
Labels: setting, frontend

#71 Updates
  index.html
Labels: setting, frontend

#72 Create CNAME
  CNAME
Labels: frontend

#75 Update gh-pages
  assets/index.0ff1d040.js
  index.html
Labels: frontend

#78 api 주소 새로운 주소로 바뀌어 주소 변경하였습니다.
  app-web/index.html
  app-web/src/ReservationItem.tsx
  app-web/src/ReservationListContainer.tsx
  app-web/src/reservationApi.ts
  app-web/vite.config.ts
Labels: setting, frontend

#79 CI/CD를 위한 ci.yml 파일 생성
  .github/workflows/ci.yml
Labels: setting, backend

#80 working directory 수정
  .github/workflows/ci.yml
Labels: setting, fix, backend

#82 API 주소 변경이 되었습니다.
  app-web/src/ReservationFormContainer.tsx
  app-web/src/ReservationItem.tsx
  app-web/src/ReservationListContainer.tsx
Labels: refactor, frontend

#83 github Page 변경 되었습니다.
  CNAME
  assets/index.fee6a760.js
  index.html
Labels: frontend

#88 Updates gh-pages
  assets/index.740b8224.js
  assets/index.fee6a760.js
  index.html
Labels: frontend

#91 로그인 회원가입 페이지가 필요합니다.
  app-web/package-lock.json
  app-web/package.json
  app-web/src/App.tsx
  app-web/src/Header.tsx
  app-web/src/NotFound.tsx
  app-web/src/ReservationListContainer.tsx
  app-web/src/api.ts
  app-web/src/components/Header.tsx
  app-web/src/main.tsx
  app-web/src/reservationApi.ts
  app-web/src/signIn.tsx
  app-web/src/signInContainer.tsx
  app-web/src/signUp.tsx
Labels: feature, frontend

#94 Updates
  assets/index.369cae3d.js
  index.html
Labels: frontend

#95 Updates
  assets/index.b13d67be.js
  index.html
Labels: frontend

#96 API가 바뀌었습니다.
  app-web/src/ReservationFormContainer.tsx
  app-web/src/api.ts
  app-web/src/main.tsx
Labels: setting, frontend

#98 userName과 seatNumber가 2개의 인자입니다
  app-web/src/ReservationListContainer.tsx
  app-web/src/api.ts
Labels: frontend

#90 당일 예약 내역 유무에 따라 예약 가능 여부를 결정하는 로직 추가
  app-server/app/src/main/java/com/codesoom/myseat/controllers/ControllerErrorAdvice.java
  app-server/app/src/main/java/com/codesoom/myseat/exceptions/UserAlreadyReservedSeatTodayException.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SeatReservationService.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SeatReservationServiceTest.java
Labels: feature, backend

#101 회원 가입 기능 구현
  app-server/app/src/main/java/com/codesoom/myseat/controllers/SignupController.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/User.java
  app-server/app/src/main/java/com/codesoom/myseat/domain/UserRepository.java
  app-server/app/src/main/java/com/codesoom/myseat/dto/SignupRequest.java
  app-server/app/src/main/java/com/codesoom/myseat/services/SignupService.java
  app-server/app/src/test/java/com/codesoom/myseat/controllers/SignupControllerTest.java
  app-server/app/src/test/java/com/codesoom/myseat/services/SignupServiceTest.java
Labels: feature, backend

#105 Read.me 업데이트 하였습니다.
  README.md
  app-web/src/ReservationListContainer.tsx
  app-web/src/Users.tsx
  app-web/src/api.ts
  app-web/src/main.tsx
  app-web/src/signIn.tsx
  app-web/src/signInContainer.tsx
  app-web/src/signUp.tsx
  app-web/src/signUpContainer.tsx
Labels: setting
